spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  management:
    endpoints:
      web:
        exposure:
          include: health,beans,loggers
          # custom actuator base path: use root mapping `/` instead of default `/actuator/`
        base-path: /carpooling
        # override endpoint name for health check: `/health` => `/status`
        path-mapping:
          health=/ping/me: /status
      security:
        enabled: false


